---
- name: install mariadb
  yum:
    name: mariadb
    state: lstest
- name: install mariadb server
  yum:
    name: mariadb-server
    state: latest
- name: install php-mysql
  yum:
    name: php-mysql
    state: latest
- name: start mariadb
  service:
    name: mariadb
    satate: started 
